
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  binary: kubectl-bulk
  main: ./cmd/kubectl-bulk
  goos:
    - freebsd
    - linux
    - windows
  goarch:
    - amd64
    - 386
    - arm
    - arm64
archive:
  format: tar.gz
archives:
- replacements:
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
